// <auto-generated />
namespace TeaShop_BetaTea.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserAvatar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAvatar));
        
        string IMigrationMetadata.Id
        {
            get { return "202105210312360_UserAvatar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
